In [74]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.datasets import fetch_openml
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix

#!pip install tensorflow
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow import keras

#!pip install seaborn
import seaborn as sns

In [46]:
path = ''
file = 'Placement_Data_Full_Class.csv'

df = pd.read_csv(path + file)
df = df.dropna()

#array of categorical variables to encode
#prefix=['gender', 'ssc_b', 'hsc_b', 'hsc_s', 'degree_t', 'workex', 'specialisation', 'status'] 

# Perform one-hot encoding, add columns for each categorical variable
#df_encoded = pd.get_dummies(df, prefix)

#print(df)
#print(df_encoded)

In [61]:
X = df.drop(['degree_t'], axis=1)
X = pd.get_dummies(X)

# Select the dependent variable
y = df['degree_t'] 
y = pd.get_dummies(y)
print(X)

     sl_no  ssc_p  hsc_p  degree_p  etest_p  mba_p    salary  gender_F  \
0        1  67.00  91.00     58.00     55.0  58.80  270000.0         0   
1        2  79.33  78.33     77.48     86.5  66.28  200000.0         0   
2        3  65.00  68.00     64.00     75.0  57.80  250000.0         0   
4        5  85.80  73.60     73.30     96.8  55.50  425000.0         0   
7        8  82.00  64.00     66.00     67.0  62.14  252000.0         0   
..     ...    ...    ...       ...      ...    ...       ...       ...   
209    210  62.00  72.00     65.00     67.0  56.49  216000.0         0   
210    211  80.60  82.00     77.60     91.0  74.49  400000.0         0   
211    212  58.00  60.00     72.00     74.0  53.62  275000.0         0   
212    213  67.00  67.00     73.00     59.0  69.72  295000.0         0   
213    214  74.00  66.00     58.00     70.0  60.23  204000.0         1   

     gender_M  ssc_b_Central  ...  hsc_b_Central  hsc_b_Others  hsc_s_Arts  \
0           1              0  ...

In [54]:
# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [55]:
# This creates our first MLP with 1 hidden layer with 50 neurons and sets it to run through the data 20 times
mlp1 = MLPClassifier(hidden_layer_sizes=(200,200, 200), max_iter=20, alpha=1e-4,
                    solver='sgd', verbose=10, tol=1e-4, random_state=1,
                    learning_rate_init=.1)

print("Created our first MLP network")

Created our first MLP network


In [56]:
#train the NN
mlp1.fit(X_train, y_train)
print("Training set score: %f" % mlp1.score(X_train, y_train))
print("Test set score: %f" % mlp1.score(X_test, y_test))

Iteration 1, loss = 72.08749558
Iteration 2, loss = 2631.21794039
Iteration 3, loss = 25655475483455539716993056768.00000000
Iteration 4, loss = 52192894085851310905588973568.00000000
Iteration 5, loss = 3505528810561617998619094192118316963794501238784.00000000
Iteration 6, loss = 12372671650901645121667824553493385523754052878336.00000000
Iteration 7, loss = 22146840863710001170035428020731813492877336510464.00000000
Iteration 8, loss = 33454903222299944681584687821651904164943682863104.00000000
Iteration 9, loss = 45666315541160797978379184178286698780546918514688.00000000
Iteration 10, loss = 58304247625113982304904653901532217308511826083840.00000000
Iteration 11, loss = 71012985932073366119562970543242085260115000164352.00000000
Iteration 12, loss = 83531869605763824821579974031428125090560266469376.00000000
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.
Training set score: 0.661017
Test set score: 0.800000


In [58]:
# STEP 3.2

# First let's initialize a list with all the predicted values from the training set
y_pred = mlp1.predict(X_test)

print(y_pred)
print(X_test)

# Now let's visualize the errors between the predictions and the actual labels using a confusion matrix
cm = confusion_matrix(y_test, y_pred)
plt.matshow(cm)

[[1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]]
     sl_no  ssc_p  hsc_p  degree_p  etest_p  mba_p    salary  gender_F  \
178    179  68.00  56.00     68.00    73.00  68.07  350000.0         0   
74      75  56.60  64.80     70.20    84.27  67.20  336000.0         0   
203    204  55.68  61.33     56.87    66.00  58.30  260000.0         0   
28      29  76.76  76.50     67.50    73.35  64.15  350000.0         0   
145    146  89.40  65.66     71.25    72.00  63.23  400000.0         0   
20      21  62.00  65.00     66.00    50.00  56.70  265000.0         0   
112    113  58.00  61.00     61.00    58.00  53.94  250000.0         0   
48      49  63.00  62.00     68.00    64.00  62.46  250000.0         0   
117    118  77.00  75.00     73.00    80.00  67.05  240000.0   

ValueError: multilabel-indicator is not supported

In [67]:
# Load your data with multiple variables into a DataFrame
data = {
    'Variable1': [1, 2, 3, 4, 5, 6, 7, 8],
    'Variable2': [5, 6, 7, 8, 9, 10, 11, 12],
    'Variable3': [9, 10, 11, 12, 13, 14, 15, 16],
    'Variable4': [13, 14, 15, 16, 17, 18, 19, 20],
    'Target': ['ClassA', 'ClassB', 'ClassC', 'ClassA', 'ClassB', 'ClassC', 'ClassA', 'ClassB']
}
df = pd.DataFrame(data)

# Split the dataset into input features (X) and target variable (y)
X = df.drop('Target', axis=1)  # Exclude the target variable
y = df['Target']

# One-hot encode the categorical target variable
y_encoded = pd.get_dummies(y)

# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42)

# Define the neural network architecture
model = keras.Sequential([
    keras.layers.Dense(32, activation='relu', input_shape=(X.shape[1],)),
    keras.layers.Dense(16, activation='relu'),
    keras.layers.Dense(y_encoded.shape[1], activation='softmax')
])

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train, epochs=10, batch_size=32)

# Evaluate the model on the test set
loss, accuracy = model.evaluate(X_test, y_test)
print('Test loss:', loss)
print('Test accuracy:', accuracy)


Epoch 1/10
1/1 [==============================] - 1s 584ms/step - loss: 2.0540 - accuracy: 0.5000
Epoch 2/10
1/1 [==============================] - 0s 12ms/step - loss: 1.9224 - accuracy: 0.5000
Epoch 3/10
1/1 [==============================] - 0s 12ms/step - loss: 1.7917 - accuracy: 0.5000
Epoch 4/10
1/1 [==============================] - 0s 12ms/step - loss: 1.6655 - accuracy: 0.5000
Epoch 5/10
1/1 [==============================] - 0s 21ms/step - loss: 1.5458 - accuracy: 0.5000
Epoch 6/10
1/1 [==============================] - 0s 19ms/step - loss: 1.4343 - accuracy: 0.5000
Epoch 7/10
1/1 [==============================] - 0s 11ms/step - loss: 1.3327 - accuracy: 0.5000
Epoch 8/10
1/1 [==============================] - 0s 12ms/step - loss: 1.2420 - accuracy: 0.5000
Epoch 9/10
1/1 [==============================] - 0s 10ms/step - loss: 1.1657 - accuracy: 0.5000
Epoch 10/10
1/1 [==============================] - 0s 110ms/step - loss: 1.6803 - accuracy: 0.0000e+00
Test loss: 1.6803014278

In [73]:

# First let's initialize a list with all the predicted values from the training set
y_pred = model.predict(X_test)
print(y_pred)
y_pred = y_pred.astype(int)
print(y_test)
print(y_pred)

# Now let's visualize the errors between the predictions and the actual labels using a confusion matrix
cm = confusion_matrix(y_test, y_pred)
plt.matshow(cm)

1/1 [==============================] - 0s 41ms/step
[[0.7013209  0.16744353 0.13123554]
 [0.5839777  0.20870276 0.20731962]]
   ClassA  ClassB  ClassC
1       0       1       0
5       0       0       1
[[0 0 0]
 [0 0 0]]


ValueError: multilabel-indicator is not supported

In [53]:
# Define the neural network architecture
model = keras.Sequential([
    keras.layers.Dense(32, activation='relu', input_shape=(21,)),
    keras.layers.Dense(16, activation='relu'),
    keras.layers.Dense(1, activation='softmax')
])

# Compile the model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X, y, epochs=10, batch_size=32)

# Make predictions
predictions = model.predict(X)

# Print the predicted classes
predicted_classes = tf.argmax(predictions, axis=1)
print(predicted_classes)

Epoch 1/10


2023-07-05 00:17:43.853952: I tensorflow/core/common_runtime/executor.cc:1197] [/job:localhost/replica:0/task:0/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: logits and labels must have the same first dimension, got logits shape [32,1] and labels shape [96]
	 [[{{node sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits}}]]


InvalidArgumentError: Graph execution error:

Detected at node 'sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits' defined at (most recent call last):
    File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "/home/malpizar/Documents/notebook/jupyter_env/lib/python3.8/site-packages/ipykernel_launcher.py", line 16, in <module>
      app.launch_new_instance()
    File "/home/malpizar/Documents/notebook/jupyter_env/lib/python3.8/site-packages/traitlets/config/application.py", line 846, in launch_instance
      app.start()
    File "/home/malpizar/Documents/notebook/jupyter_env/lib/python3.8/site-packages/ipykernel/kernelapp.py", line 677, in start
      self.io_loop.start()
    File "/home/malpizar/Documents/notebook/jupyter_env/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 199, in start
      self.asyncio_loop.run_forever()
    File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
      self._run_once()
    File "/usr/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
      handle._run()
    File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
      self._context.run(self._callback, *self._args)
    File "/home/malpizar/Documents/notebook/jupyter_env/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 461, in dispatch_queue
      await self.process_one()
    File "/home/malpizar/Documents/notebook/jupyter_env/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 450, in process_one
      await dispatch(*args)
    File "/home/malpizar/Documents/notebook/jupyter_env/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 357, in dispatch_shell
      await result
    File "/home/malpizar/Documents/notebook/jupyter_env/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 652, in execute_request
      reply_content = await reply_content
    File "/home/malpizar/Documents/notebook/jupyter_env/lib/python3.8/site-packages/ipykernel/ipkernel.py", line 353, in do_execute
      res = shell.run_cell(code, store_history=store_history, silent=silent)
    File "/home/malpizar/Documents/notebook/jupyter_env/lib/python3.8/site-packages/ipykernel/zmqshell.py", line 532, in run_cell
      return super().run_cell(*args, **kwargs)
    File "/home/malpizar/Documents/notebook/jupyter_env/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2768, in run_cell
      result = self._run_cell(
    File "/home/malpizar/Documents/notebook/jupyter_env/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2814, in _run_cell
      return runner(coro)
    File "/home/malpizar/Documents/notebook/jupyter_env/lib/python3.8/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
      coro.send(None)
    File "/home/malpizar/Documents/notebook/jupyter_env/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3012, in run_cell_async
      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
    File "/home/malpizar/Documents/notebook/jupyter_env/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3191, in run_ast_nodes
      if await self.run_code(code, result, async_=asy):
    File "/home/malpizar/Documents/notebook/jupyter_env/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3251, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "/tmp/ipykernel_7373/1912084938.py", line 12, in <module>
      model.fit(X, y, epochs=10, batch_size=32)
    File "/home/malpizar/Documents/notebook/jupyter_env/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/home/malpizar/Documents/notebook/jupyter_env/lib/python3.8/site-packages/keras/engine/training.py", line 1685, in fit
      tmp_logs = self.train_function(iterator)
    File "/home/malpizar/Documents/notebook/jupyter_env/lib/python3.8/site-packages/keras/engine/training.py", line 1284, in train_function
      return step_function(self, iterator)
    File "/home/malpizar/Documents/notebook/jupyter_env/lib/python3.8/site-packages/keras/engine/training.py", line 1268, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/home/malpizar/Documents/notebook/jupyter_env/lib/python3.8/site-packages/keras/engine/training.py", line 1249, in run_step
      outputs = model.train_step(data)
    File "/home/malpizar/Documents/notebook/jupyter_env/lib/python3.8/site-packages/keras/engine/training.py", line 1051, in train_step
      loss = self.compute_loss(x, y, y_pred, sample_weight)
    File "/home/malpizar/Documents/notebook/jupyter_env/lib/python3.8/site-packages/keras/engine/training.py", line 1109, in compute_loss
      return self.compiled_loss(
    File "/home/malpizar/Documents/notebook/jupyter_env/lib/python3.8/site-packages/keras/engine/compile_utils.py", line 265, in __call__
      loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "/home/malpizar/Documents/notebook/jupyter_env/lib/python3.8/site-packages/keras/losses.py", line 142, in __call__
      losses = call_fn(y_true, y_pred)
    File "/home/malpizar/Documents/notebook/jupyter_env/lib/python3.8/site-packages/keras/losses.py", line 268, in call
      return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "/home/malpizar/Documents/notebook/jupyter_env/lib/python3.8/site-packages/keras/losses.py", line 2078, in sparse_categorical_crossentropy
      return backend.sparse_categorical_crossentropy(
    File "/home/malpizar/Documents/notebook/jupyter_env/lib/python3.8/site-packages/keras/backend.py", line 5660, in sparse_categorical_crossentropy
      res = tf.nn.sparse_softmax_cross_entropy_with_logits(
Node: 'sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits'
logits and labels must have the same first dimension, got logits shape [32,1] and labels shape [96]
	 [[{{node sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits}}]] [Op:__inference_train_function_1159]